maps_manager_node:
  ros__parameters:
    use_sim_time: false
    map_types: ["navmap"]

    navmap:
      plugin: "navmap_file_loader/NavmapFileLoader"
      map_file: "/Rolling/navmap/tb3.navmap"
      frame_id: "map"
