maps_manager_node:
  ros__parameters:
    use_sim_time: false
    map_types: ["navmap"]

    navmap:
      plugin: "easynav::NavmapFileLoader"
      map_file: "/absolute/path/to/data/output/tb3.navmap"
      frame_id: "map"

